### ISSUE TITLE
Shape Variation Analyzer fails to load

### ISSUE THREAD

**Issue by bpaniagua** [DCBIA-OrthoLab/SlicerCMF#18] opened 2020-09-17 16:38 UTC
**OS** 
![Screen Shot 2020-09-17 at 12 37 14 PM](https://user-images.githubusercontent.com/2599368/93500777-896ada00-f8e2-11ea-8f49-1f8f45bd64c5.png)

**Slicer version**
![Screen Shot 2020-09-17 at 12 37 50 PM](https://user-images.githubusercontent.com/2599368/93500832-9ee00400-f8e2-11ea-9fab-60f9769c9fdc.png)

**Error log**

![Screen Shot 2020-09-17 at 12 35 50 PM](https://user-images.githubusercontent.com/2599368/93500657-64766700-f8e2-11ea-8390-754ac457f1f2.png)

**Other notes**

SVA fails to load, probably because of  shapepcalib that fails to be loaded?

@allemangD could you please look into this?

**Comment by allemangD** [comment] 2020-09-17 16:57
The issue is also tracked in https://github.com/DCBIA-OrthoLab/ShapeVariationAnalyzer/issues/54

**Comment by bpaniagua** [comment] 2020-09-17 17:10
👍

**Comment by allemangD** [comment] 2021-06-30 13:10
Closing as duplicate.

**Closed as completed by allemangD** 2021-06-30 13:10 UTC
